### ISSUE TITLE
integrate redis tests

### ISSUE THREAD

**Issue by siddontang** [reborndb/qdb#14]
@qiuyesuifeng 

If we can pass Redis tests(not including lost feature like AOF, zipmap, sentinel, etc.), I think we can guarantee that qdb is robust and stable. 

Redis tests uses TCL which is very easy and we may add our slots tests too. 

But at first, I think we should refactor whole test framework using gocheck instead. I don't like old test, e.g, for service, olds tests uses a fake session but I prefer real tcp connection like in production environment.

**Comment by ngaut** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
using gocheck for qdb test has been done.
