### ISSUE TITLE
setup.sh fails on linux platform

### ISSUE THREAD

**Issue by yinhm** [reborndb/qdb#34]
librocksdb.dylib is OSX specific, on linux platform, default to .so 

```
$ git diff
diff --git a/extern/setup.sh b/extern/setup.sh
index 235063a..5ad8401 100755
--- a/extern/setup.sh
+++ b/extern/setup.sh
@@ -13,7 +13,7 @@ cd ./rocksdb; make clean
 make -j4 shared_lib && cd .. || exit 1
 
 cp -rf rocksdb/include/rocksdb ${BUILD}
-cp -f rocksdb/librocksdb.dylib ${BUILD}
+cp -f rocksdb/librocksdb.* ${BUILD}
 
 cd ./levigo
 CGO_CFLAGS="-I${BUILD}" CGO_LDFLAGS="-L${BUILD} -lleveldb -lsnappy -lstdc++" go install ./
```

**Comment by qiuyesuifeng** [comment]
thanks.  @yinhm 

we mainly work and test on OSX, so not support linux now.
also,  there are so many dependencies, like libsnappy and so on.
after finishing qdb and reborn's new features, we will work on it.
warmly welcome you to do a pull request :)

**Comment by siddontang** [comment]
Thanks @yinhm 

Building leveldb and rocksdb in different platforms like linux, macosx is not an easy thing, especially for rocksdb, so later we may recommend user to read rocksdb's manual first and then build, not directly using setup.sh. 

We develop qdb in mac osx mainly, but we support it in linux too. The setup.sh is our fault, thank you very much.

**Comment by yinhm** [comment]
Maybe qdb could move rocksdb out of repository, and provide a build example using Vagrant and Docker like cockroach what did: https://github.com/cockroachdb/cockroach/tree/master/build

It may hard the build process further, but good for CI.

**Comment by qiuyesuifeng** [comment]
Yeah. Using Vagrant and Docker is a good idea.
But firstly, we will modify setup.sh and add a simple bootstrap shell to build environment easily.
Later there will be a new branch to do it.
Thank u for suggestion.

**Comment by qiuyesuifeng** [comment]
@yinhm  
See #40.
In further there will a docker version. 
But now, u can use bootstrap.sh for easily build.
Any question, u can contact us.
