### ISSUE TITLE
Make qdb embed and extent friendly

### ISSUE THREAD

**Issue by yinhm** [reborndb/qdb#36]
I understand qdb was tailored for reborndb, but it would be nice if qdb more friendly to embed and more extendable.

For example:

```
func Serve(config *Config, bl *store.Store) error {
	h, err := newHandler(config, bl)
	if err != nil {
		return errors.Trace(err)
	}

	defer h.close()

	err = h.run()
	return errors.Trace(err)
}
```

May be change to a Server struct, and serve from Server instance.

```
type Server struct {
    *Handler
}

func NewServer() *Server {}
func (srv *server) Serve() error {}
```

Or make newHandler a public method.

For the extend part, I think https://github.com/bsm/redeo was a good example, https://github.com/alicebob/miniredis using it implemented a redis for unittests.

redeo example of echo:

```
  srv := redeo.NewServer(&redeo.Config{Addr: "localhost:9736"})
  srv.HandleFunc("ping", func(out *redeo.Responder, _ *redeo.Request) error {
    out.WriteInlineString("PONG")
    return nil
  })
```

It let user define handler in a idiomatic way, I really wish qdb could expose a fully compatible redis and also let user extend(define) more commands(Handle Func).

**Comment by qiuyesuifeng** [comment]
Thanks. @yinhm 

In branch fix-value-set-bug, we have made newHandler and handler's run/close function exported.
Also remove Serve func by using NewHandler and Run func instead.
Now cmd processing funcs using a mini reflect package to register into HandlerTable.
We will discuss it later on how to support user define funcs better.

**Comment by siddontang** [comment]
Thanks @yinhm 

We will refactor the code as you said above. We will supply a Server struct embedding Handler. 

Btw, Handler is the old source and I don't like the reflect implementation, maybe later we will use simply  registering command name and function. 

Your valuable advice is very welcome. :-)

**Comment by siddontang** [comment]
See https://github.com/reborndb/qdb/pull/38

**Comment by yinhm** [comment]
@siddontang great to see things moving fast.

With #38 commit there is a problem, what I really want is the Api exposed by Server struct, for example: Server.Handler.Set, Server.Handler.Get. 

@qiuyesuifeng changes in fix-value-set-bug branch allow me to do that.

I really wish server can call src.Handler.Get, etc, and let us extend Handler method there ultimately.

**Comment by siddontang** [comment]
@yinhm 

I prefer supplying a register function like `func Register(name string, c Command)` later, not exposing Handler. 

Btw, I don't know how do you extend Handler dynamically.

**Comment by ngaut** [comment]
I do agree @siddontang

**Comment by yinhm** [comment]
@siddontang A Register method would be fine. I probably should say user define command(Handler) instead  of  extend Handler?

In a idiomatic way, we could do:

```
  srv.HandleFunc("GetTicks", func(out *redeo.Responder, _ *redeo.Request) error {
    out.WriteInlineString("ALL TICKS YOU WANT IS HERE")
    return nil
  })
```

The internal qdb could use this HandleFunc to register redis command as well.  

The reason I need it is that I have a legacy project which using the redis protocol, I'm migrate it to rocksdb, found out that I may have many implementation detail just like qdb, and clearly qdb will be well maintained. 

But qdb was not friendly embed, for example, if I want GetTicks talks like redis protocol, I need:

 - Api to register GetTicks to qdb,
 - Call Handler.Methods direclty, otherwise I have to use redis://:locahost:6397

Hope I made my motivation clear now, what's your suggestion?

**Comment by yinhm** [comment]
Maybe call Handler.Methods direclty wasn't really necessary if I can extend the redis commands just like the internal qdb.

**Comment by siddontang** [comment]
@yinhm 

I think what you said above is the same as my said, a register function like HTTP HandleFunc or Handle.The register function may like below or other:

```
func (s *Server) Register(name string, f func(args ...[][]byte) (redis.Resp, error)) 
```

Because all the request args in Redis protocol is array of bulk string, so args is [][]byte. 
In the function, you can do anything (using backend store API to do something) and then return a redis protocol object (see reborndb/go/redis/resp) or error.

I know that your product supports Redis protocol, so I think we should not call Handler method directly and only use protocol through network.

**Comment by yinhm** [comment]
I still need to utilize the underlying storage in the same way Handler did.  I just realized what handle method did was just calling session and other helper methods, it was not really couple with handle struct, so I think it would be fine(with a Register function).

**Comment by siddontang** [comment]
I got it. 
Maybe we can supply GetStorage function. @yinhm , is it your need too?

@qiuyesuifeng

**Comment by yinhm** [comment]
It would be great.

**Comment by qiuyesuifeng** [comment]
@yinhm 
Ok, i will provide a function to get background store engine in a further version.

**Comment by siddontang** [comment]
@yinhm 

We will pass a store object when create Server, so you can use this store directly. You can see qdb/cmd/qdb-server/main.go for more information.

**Comment by qiuyesuifeng** [comment]
@yinhm 
In addition, now u can a server backgroud store.
For example,
```
testdb := xxxx
cfg := xxxx

store := store.New(testdb)
server, err := NewServer(cfg, store)
go server.Serve()
```

so u can get store and do something.
maybe that is what u want?

**Comment by siddontang** [comment]
Hi @yinhm , we will discuss this feature here #51
