### ISSUE TITLE
use goleveldb for test

### ISSUE THREAD

**Issue by siddontang** [reborndb/qdb#48]
@qiuyesuifeng

**Comment by siddontang** [comment]
The goleveldb's performance is not good, many ttl tests can not pass, so we may still use rocksdb for test .

**Comment by qiuyesuifeng** [comment]
ok,  how about boltdb(https://github.com/boltdb/bolt)? can it be built a store engine for test?

**Comment by siddontang** [comment]
Now, boltdb is slow too, maybe I think we should use rocksdb or leveldb yet.

**Comment by qiuyesuifeng** [comment]
got it.

**Comment by yinhm** [comment]
Why not stick to rocksdb? Too many storage engines comes with costs: harder to maintain, harder to deploy, harder to use high level feature introduced by upstream(engine).

I really really wish qdb pick the best one, stick to it, then make it shiny.

**Comment by siddontang** [comment]
@yinhm 

We mainly use rocksdb, but why not goleveldb is that some people just want to use pure go version for a try, as you see, building rocksdb is not easy.

But we don't recommend user to use goleveldb in production environment.

Why supporting leveldb is that rocksdb and leveldb are both robust and stable, and some people prefer rocksdb but others prefer leveldb :-)

**Comment by yinhm** [comment]
@siddontang frankly this make things more complicated, influxdb used to adapted to many storage engines but migrated to blotdb in 0.9[1], another example is cockroachdb which is sticked to rocksdb and it is just fine.

[1] https://influxdb.com/blog/2014/12/08/clustering_tags_and_enhancements_in_0_9_0.html

**Comment by siddontang** [comment]
Thanks, we will consider it. 

@ngaut how do you think?

**Comment by siddontang** [comment]
We will still use rocksdb for qdb test.
