### ISSUE TITLE
service supports sync and psync

### ISSUE THREAD

**Issue by siddontang** [reborndb/qdb#5]
@ngaut  @c4pt0r 

Now service doesn't support psync and sync.

slaveof only supports sync.

**Comment by c4pt0r** [comment]
yep, SYNC and PSYNC are both necessary.

**Comment by siddontang** [comment]
@ngaut @c4pt0r 

Refer redis

+ Supply replication backlog buffer to transfer modified changes to slaves.
+ Master write changes using binlog Forward information into backlog after (or before???) rocksdb/leveldb commit. 
+ Master receives sync or psync command, save a dump with current replication offset, or reuse an old dump.
+ After master sends dump into slave, master will send incremental data to slave from above replication offset in replication backlog buffer. 

Caveat

Let's consider this scenario, we save a dump with replication offset (e.g, 1000), and the replication backlog size is 1G,  if we have many write operations, after master sends dump to slave, the offset 1000 is not in replication backlog buffer.

To solve this, we may have a bigger backlog buffer or using file. Any thoughts?
