### ISSUE TITLE
remove reflect, add Register for qdb

### ISSUE THREAD

**Issue by siddontang** [reborndb/qdb#51]
1, Remove old reflect for registering commands
2, Supply a Register function like `func Register(name string, f func(...))` to register commands and let other people register their self commands.  

@qiuyesuifeng, we may define the Register function below.

**Comment by qiuyesuifeng** [comment]
yeah, agreed, much better.

**Comment by qiuyesuifeng** [comment]
see #53

**Comment by yinhm** [comment]
thanks for the updates, even thought I still want to call command like GetSet directly from server which is where qdb embed, I'm fine with this change. The following is the example code I'm using:

```
// redis commands
// GetMtime key [key ...]
func (s *ApiServer) GetMtimeCmd(sess qdbService.Session, args [][]byte) (redis.Resp, error) {
	if len(args) < 1 {
		err := errors.Errorf("len(args) = %d, expect >= 1", len(args))
		return redis.NewError(err), err
	}

	if b, err := sess.Store().Get(sess.DB(), iconvert(args)...); err != nil {
		return redis.NewError(err), err
	} else {
		return redis.NewBulkBytes(b), nil
	}
}

func iconvert(args [][]byte) []interface{} {
	iargs := make([]interface{}, len(args))
	for i, v := range args {
		iargs[i] = v
	}
	return iargs
}
```

close #36

**Comment by yinhm** [comment]
It would be great if I can just return 

```
return sess.Store().Get(sess.DB(), iconvert(args)...)
```

as the callback func which is passing to Register function.

**Comment by siddontang** [comment]
Hi @yinhm , I don't like iconvert(args) very much. This is the old source, and I find it is useless, may be later we will later store api use [][]byte directly. 

What you mean may be that you want to let us check the return data type and do like `redis.NewBulkBytes` by ourself, not in register function. Am I right?

**Comment by yinhm** [comment]
@siddontang Right. I'm sure is this doable. I'm fine with current implementation.

**Comment by siddontang** [comment]
I know that my LedisDB do the same thing, so I think we can support it too.

**Comment by siddontang** [comment]
Hi @yinhm  @qiuyesuifeng 

I try to create a branch to help user write its own functions easily. You can a simple example here: 

https://github.com/reborndb/qdb/blob/register-improvement/pkg/service/command_test.go

https://github.com/reborndb/qdb/blob/register-improvement/pkg/service/command.go

I supply multi register functions but not only one like `Register` because I don't like reflect. :-)

**Comment by qiuyesuifeng** [comment]
LGTM
