### ISSUE TITLE
is it deleteIfExists necessary in set command

### ISSUE THREAD

**Issue by siddontang** [reborndb/qdb#72]
I see that set* commands use deleteIfExists, but is it necessary? 

We should check the source exactly and add more tests.

@qiuyesuifeng

**Comment by qiuyesuifeng** [comment]
yeah, i think that it is no use to deleteIfExists in Set func.

**Comment by ngaut** [comment]
redis support some wired operation. Let's say you hava a list A.
Then you do set A xx to replace it. Now A is a string !!

**Comment by siddontang** [comment]
Got it.
But I still think this is a horrible feature.

**Comment by ngaut** [comment]
I do agree, we have to support it if we want compatibility.

**Comment by qiuyesuifeng** [comment]
ok, got it.
