### ISSUE TITLE
安装qdb时遇到问题。帮忙指点一下

### ISSUE THREAD

**Issue by jianhuihi** [reborndb/qdb#90]
++ pwd
+ BUILD_PATH=/home/qdb/extern
+ INSTALL_PATH=/usr/local
+ CXX=gcc
+ test -d /usr/local/include
+ test -d /usr/local/lib
+ gcc -x c++ - -o /dev/null
+ '[' 0 -ne 0 ']'
+ gcc -x c++ - -o /dev/null -lleveldb
+ '[' 0 -ne 0 ']'
+ gcc -x c++ - -o /dev/null -lrocksdb
+ '[' 1 -ne 0 ']'
+ cd /home/qdb/extern/rocksdb
+ make -j4 shared_lib
g++ -shared -Wl,-soname -Wl,librocksdb.so -g -Wall -Werror -Wsign-compare -Wshadow -I. -I./include -std=c++11  -DROCKSDB_PLATFORM_POSIX  -DOS_LINUX -fno-builtin-memcmp -DROCKSDB_FALLOCATE_PRESENT -DSNAPPY -DZLIB -DBZIP2   -DHAVE_JEMALLOC -O2 -fno-omit-frame-pointer -momit-leaf-frame-pointer -DNDEBUG -Woverloaded-virtual -Wnon-virtual-dtor -fPIC db/builder.cc db/c.cc db/column_family.cc db/compaction.cc db/compaction_job.cc db/compaction_picker.cc db/db_filesnapshot.cc db/db_impl.cc db/db_impl_debug.cc db/db_impl_readonly.cc db/db_iter.cc db/dbformat.cc db/file_indexer.cc db/filename.cc db/flush_job.cc db/flush_scheduler.cc db/forward_iterator.cc db/internal_stats.cc db/log_reader.cc db/log_writer.cc db/memtable.cc db/memtable_list.cc db/merge_helper.cc db/merge_operator.cc db/repair.cc db/table_cache.cc db/table_properties_collector.cc db/transaction_log_impl.cc db/version_builder.cc db/version_edit.cc db/version_set.cc db/wal_manager.cc db/write_batch.cc db/write_controller.cc db/write_thread.cc table/adaptive_table_factory.cc table/block.cc table/block_based_filter_block.cc table/block_based_table_builder.cc table/block_based_table_factory.cc table/block_based_table_reader.cc table/block_builder.cc table/block_hash_index.cc table/block_prefix_index.cc table/bloom_block.cc table/cuckoo_table_builder.cc table/cuckoo_table_factory.cc table/cuckoo_table_reader.cc table/flush_block_policy.cc table/format.cc table/full_filter_block.cc table/get_context.cc table/iterator.cc table/merger.cc table/meta_blocks.cc table/plain_table_builder.cc table/plain_table_factory.cc table/plain_table_index.cc table/plain_table_key_coding.cc table/plain_table_reader.cc table/table_properties.cc table/two_level_iterator.cc util/arena.cc util/auto_roll_logger.cc util/blob_store.cc util/bloom.cc util/build_version.cc util/cache.cc util/coding.cc util/comparator.cc util/crc32c.cc util/db_info_dumper.cc util/dynamic_bloom.cc util/env.cc util/env_hdfs.cc util/env_posix.cc util/filter_policy.cc util/hash.cc util/hash_cuckoo_rep.cc util/hash_linklist_rep.cc util/hash_skiplist_rep.cc util/histogram.cc util/iostats_context.cc util/ldb_cmd.cc util/ldb_tool.cc util/log_buffer.cc util/logging.cc util/murmurhash.cc util/mutable_cf_options.cc util/options.cc util/options_builder.cc util/options_helper.cc util/perf_context.cc util/rate_limiter.cc util/skiplistrep.cc util/slice.cc util/sst_dump_tool.cc util/statistics.cc util/status.cc util/string_util.cc util/sync_point.cc util/thread_local.cc util/vectorrep.cc util/xxhash.cc utilities/backupable/backupable_db.cc utilities/compacted_db/compacted_db_impl.cc utilities/document/document_db.cc utilities/document/json_document.cc utilities/geodb/geodb_impl.cc utilities/merge_operators/put.cc utilities/merge_operators/string_append/stringappend.cc utilities/merge_operators/string_append/stringappend2.cc utilities/merge_operators/uint64add.cc utilities/redis/redis_lists.cc utilities/spatialdb/spatial_db.cc utilities/ttl/db_ttl_impl.cc utilities/write_batch_with_index/write_batch_with_index.cc  port/stack_trace.cc port/port_posix.cc   -lpthread -lrt -lsnappy -lz -lbz2 -o librocksdb.so
util/options_builder.cc: In function 'void rocksdb::{anonymous}::OptimizeForLevel(int, int, uint64_t, rocksdb::Options*)':
util/options_builder.cc:164:23: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
cc1plus: all warnings being treated as errors
make: *** [librocksdb.so] Error 1
+ cp -rf /home/qdb/extern/rocksdb/include/rocksdb /usr/local/include
+ cp -f '/home/qdb/extern/rocksdb/librocksdb.*' /usr/local/lib
cp: cannot stat `/home/qdb/extern/rocksdb/librocksdb.*': No such file or directory

centos 6.5 
gcc版本 4.7.2

**Comment by siddontang** [comment]
It seems that the rocksdb version 3.8 is not suitable for your compiling environment, and we find that someone else meets the same error https://github.com/facebook/rocksdb/pull/99,  you can change your makefile like this https://github.com/facebook/rocksdb/commit/f9d0530213da1a88a53d2476557309183dcce715 and have a try.  

Later we will try to update the newest RocksDB version. Thanks.

**Comment by jianhuihi** [comment]
thanks~ 

I Will try

**Comment by jianhuihi** [comment]
It's done.

**Comment by siddontang** [comment]
:-)
