### ISSUE TITLE
--create 已经不能用了吗？

### ISSUE THREAD

**Issue by jianhuihi** [reborndb/qdb#92]
如题

怎么让程序后台运行呢？

另外
如有QQ联系方式或者Q群，能方便告知一下吗？

**Comment by siddontang** [comment]
qdb has no `--create` command flag. 
sorry that we don't use QQ, if you have any problem, please create issues, we will reply you as soon as possible.

**Comment by jianhuihi** [comment]
我看文档还在用 $ qdb-server -c conf/config.toml -n 4 --create

问题是：怎么让qdb以守护进程的方式运行呢？

**Comment by siddontang** [comment]
We will update the document later, our fault. 

Go has no official way to run program in daemon, you can use other outer tool like supervisor, etc. to do this.

**Comment by jianhuihi** [comment]
明白了
